#!/bin/bash

# right=$(uptime | awk -F '[:, ]' '{print $6"d "$9"h "$10"m"}')
mem_info=$(free -m | sed -n '2p' | awk '{printf("%.2f",$3/($3+$4)*100"%")}')
cpu_info=$(sar -u 1 1 | grep Average | awk '{printf("%.2f",100-$8"%")}')
echo "CPU:"$cpu_info" MEM:"$mem_info

