#!/bin/bash

if [[ $# -ne 1 || ! -e "$1" ]]; then
    echo "$0 file_name"
    exit 1
fi

base_path=$(cd `dirname $1`; pwd)
# echo "wget -r -l 0 -nH --cut-dir 9 --retr-symlinks --preserve-permissions ftp://$(hostname):${base_path}/$(basename $1)"
echo "wget --retr-symlinks --preserve-permissions ftp://$(hostname):${base_path}/$(basename $1)"

